#!flask/bin/python
from flask import Flask, jsonify
from flask import request
import logging
from kafka import KafkaProducer
from kafka.errors import KafkaError
import base64

logger = logging.getLogger(__name__)
app = Flask(__name__)

producer = KafkaProducer(bootstrap_servers=['localhost:9092'], value_serializer=str.encode, retries=5)
status = 'running'

"""
  For possible coordinator to extract info, limited to internal call
"""
def status(status):
    status = status

@app.route('/api/v1.0/status', methods=['GET'])
def get_status():
    return jsonify({'status': status})


@app.route('/api/v1.0/submit', methods=['POST'])
def submit_signals():
    """ 
    """
    logger.info("get post request")
    print "headers", request.headers
    print request.data
    # Asynchronous by default
    sm = base64.b64decode(request.data)
    future = producer.send('api', {'theKeyForPartition': sm})
    return  'GOOD', 200 

    # block until all async messages are sent
    #producer.flush()


if __name__ == '__main__':
    app.run(debug=True)
